version: '3.9'
services:
  db:
    image: 'postgis/postgis:15-3.3'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'migration'
    ports:
      - '6433:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    command: postgres -c 'max_connections=2500'
volumes:
  db: